Fix host flash hash invalidation
The existing hash invalidation can leave slot stuck in
`HashInProgress` permanently:

```
pilot -r dublin sp exec -e 'component-active-slot host-boot-flash -s 1 -p' BRM27230037
pilot -r dublin sp exec -e 'start-host-flash-hash 0' BRM27230037
pilot -r dublin sp exec -e 'power-state A2' BRM27230037
sleep 30
pilot -r dublin sp exec -e 'power-state A0' BRM27230037
sleep 120

$ pilot -r dublin sp exec -e 'get-host-flash-hash 0' BRM27230037
Jul 28 19:22:14.066 INFO creating SP handle on interface dublin_sw0tp0, component: faux-mgs
Jul 28 19:22:14.072 INFO initial discovery complete, addr: [fe80::aa40:25ff:fe04:604%5]:11111, interface: dublin_sw0tp0, socket: control-plane-agent, component: faux-mgs
Error: Error response from SP: hf: Hash calcuation in progress
```

Switching the mux (i.e. going from Host <-> SP) should invalidate
everything and require a recalcuation. We can also end up in this
state if we write to one bank while a hash of the other bank is
in progress.

Fix this by splitting out the invalidation functions separately
and implementing them correctly. Also fix up a few other fixes
that got missed.