Add extra braces around semihosting macro
Rust complains when using the `sys_log` macro with semihosting at the
moment:

	error[E0658]: `let` expressions in this position are experimental
  --> task-jefe/src/main.rs:49:33
   |
49 | ...                   sys_log!("Task #{} Memory fault at address 0x{:x}", i, a)
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
   = help: add `#![feature(let_chains)]` to the crate attributes to enable
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

Add extra curly brackets to make it explicit what we want. This also matches
the ITM version which has brackets for an `unsafe` call.