Read env var in `task_config` proc macro (#2575)
Fixes hubris#2523

I tested this by building `app/grapefruit/rev-a.toml`, then applying
this patch and doing `cargo xtask build --dirty ...` (to avoid the
"rerun on manifest change "behavior"):

```
diff --git a/app/grapefruit/base.toml b/app/grapefruit/base.toml
index 6eaeea5f78..bcba1bc935 100644
--- a/app/grapefruit/base.toml
+++ b/app/grapefruit/base.toml
@@ -193,7 +193,7 @@

 [tasks.spartan7_loader.config]
 program_l = "sys_api::Port::B.pin(6)"
-init_l = "sys_api::Port::B.pin(5)"
+init_l = "sys_api::Port::B"
 config_done = "sys_api::Port::B.pin(4)"
 user_reset_l = "sys_api::Port::I.pin(15)"
```

```
building crate drv-spartan7-loader
   Compiling drv-spartan7-loader v0.1.0 (/Users/mjk/oxide/hubris/drv/spartan7-loader)
error[E0308]: mismatched types
   --> drv/spartan7-loader/src/main.rs:127:1
    |
127 | / task_config::task_config! {
128 | |     program_l: sys_api::PinSet,
129 | |     init_l: sys_api::PinSet,
130 | |     config_done: sys_api::PinSet,
131 | |     user_reset_l: sys_api::PinSet,
132 | | }
    | | ^
    | | |
    | |_expected `PinSet`, found `Port`
    |   in this macro invocation
    |
   ::: lib/task-config/src/lib.rs:144:1
    |
144 |   pub fn task_config(tokens: TokenStream) -> TokenStream {
    |   ------------------------------------------------------ in this expansion of `task_config::task_config!`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `drv-spartan7-loader` (bin "drv-spartan7-loader") due to 1 previous error
Error: failed to build spartan7_loader

Caused by:
    command failed, see output for details
```

This indicates that the change in task config triggered a rebuild (which
then failed).

Note that this PR removes the "include the bytes of the manifest"
behavior from the proc macro; that would not be reliable due to TOML
inheritance, and the `HUBRIS_TASK_CONFIG` environment variable is ground
truth.