Pin commits for dice-util and sprockets to fix rust-analyzer (#2480)
This is a workaround for problems running rust-analyzer. Before,
rust-analyzer was failing with:

```
LSP :: Failed to read Cargo metadata with dependencies for `~/code/hubris/Cargo.toml`: `cargo metadata` exited with an error:`
...
error: failed to select a version for the requirement `dice-mfg-msgs = "^0.2.1"`
candidate versions found which didn't match: 0.3.0
location searched: Git repository https://github.com/oxidecomputer/dice-util
required by package `lib-dice v0.1.0 (~/code/hubris/lib/dice)`
```

I believe this is independent from the `cargo xtask lsp` setup described
in the readme. I was getting this error both without that setup, and
with a (possibly broken) version of that setup modified for emacs.