ringbuf: permit trailing commas in macros (#2407)
When an invocation of one of the `ringbuf` crate's macros exceeds 80
characters in length, one is typically compelled to wrap it across
multiple lines. For instance, if I write something like:

```rust
ringbuf!(__MY_VERY_LONG_RINGBUF_NAME, MyVeryLongRingbufEntryType, 16, MyVeryLongRingbufEntryType::ThisIsALongNameForTheEntryTypesNoneVariant);
```

I would typically want to format it like this:

```rust
ringbuf!(
    __MY_VERY_LONG_RINGBUF_NAME,
    MyVeryLongRingbufEntryType,
    16,
    MyVeryLongRingbufEntryType::ThisIsALongNameForTheEntryTypesNoneVariant,
);
```

Typically, when doing things like this in Rust, one includes a trailing
comma. However, the ringbuf crate's macros do not like that:

```
error: unexpected end of macro invocation
   --> task/ereportulator/src/main.rs:76:76
    |
76  |     MyVeryLongRingbufEntryType::ThisIsALongNameForTheEntryTypesNoneVariant,
    |                                                                            ^ missing tokens in macro arguments
    |
note: while trying to match `no_dedup`
   --> /hubris/lib/ringbuf/src/lib.rs:294:47
    |
294 |     ($name:ident, $t:ty, $n:expr, $init:expr, no_dedup) => {
    |                                               ^^^^^^^^

error: unexpected end of macro invocation
   --> task/ereportulator/src/main.rs:142:72
    |
142 |                 ringbuf_entry!(Trace::EreportLost { encoded_len, err },)
    |                                                                        ^ missing tokens in macro arguments
    |
note: while trying to match meta-variable `$payload:expr`
   --> /hubris/lib/ringbuf/src/lib.rs:459:17
    |
459 |     ($buf:expr, $payload:expr) => {{
    |                 ^^^^^^^^^^^^^

error: could not compile `task-ereportulator` (bin "task-ereportulator") due to 2 previous errors
Error: failed to build ereportulator

Caused by:
    command failed, see output for details
```

This is a bit annoying. Thus, this commit updates the macros to accept
an optional trailing comma without getting upset.