Introduce new command, xtask print
This command can print out information about the build. Currently, it
only supports one option, --archive, which prints out the final build
archive. This is useful in scripting.

Example:

```
〉cargo xtask print .\app\demo-stm32f4-discovery\app.toml --archive
    Finished dev [optimized + debuginfo] target(s) in 1.68s
     Running `target\debug\xtask.exe print .\app\demo-stm32f4-discovery\app.toml --archive`
target\demo-stm32f4-discovery\dist\default\build-demo-stm32f4-discovery.zip
```

Additonally, I wanted to make the errors nice for this, and so I ended
up adding some contexts inside of the other commands, which will also
make them slightly better. Example:

```
〉cargo xtask print .\app\demo-stm32f4-discovery\app.tom --archive
    Finished dev [optimized + debuginfo] target(s) in 1.52s
     Running `target\debug\xtask.exe print .\app\demo-stm32f4-discovery\app.tom --archive`
Error: could not print information about the build

Caused by:
    0: could not create build configuration
    1: could not read .\app\demo-stm32f4-discovery\app.tom
    2: The system cannot find the file specified. (os error 2)
```