Bump sprot sizes to fix build (#1601)
#1597 bumped `syn` and `proc-macro2`.  For some reason, this slightly changes
the size of the `sprot` task, so `master` is not building for me right now:

```console
Error: task sprot: needs 47360 bytes of flash but max-sizes limits it to 47328
```

[Last time I investigated](https://matrix.to/#/!jxnlDLnJsVaIRstnrt:oxide.computer/$pCYj2H5LWUDkQwx_svMii1GZiOkXxpHA26BOjJzXPBA?via=oxide.computer&via=unix.house&via=matrix.org),
I came to the conclusion that bumping `proc-macro2` caused LLVM functions to be
emitted in a different order, which changed inlining behavior, which pushed one
task over the size limit (and there were literally no changes in the generated
LLVM IR).