ringbuf: don't allow length-0 ringbufs (#2614)
It turns out that, if you try to make a ringbuf with length 0,
surprisingly bad things will happen. This is because ringbuf entries are
written to using `get_unchecked_mut()`, in order to suppress bounds
checks. Suppressing bounds checks is okay to do, because we have already
modulo'd the index to the ringbuf's length, so it is guaranteed to be in
bounds...AS LONG AS THE LENGTH IS GREATER THAN ZERO. If it is zero,
well...`0 % 0 == 0`, so we will do `get_unchecked_mut(0)`, and
uncheckedly dereference the first index of the ringbuf array...which it
doesn't have, so you end up writing out of bounds to whatever happens to
be next to the ringbuf.

Luckily, no one has ever actually tried to make a ringbuf with zero
entries, because...why would you want that? But, just in case, it's
better if we stop you, so this branch adds a const assertion to the
ringbuf macro that checks that the length is greater than zero.

Now, if you try to make one, it fails like this: 

```
  Compiling task-ereportulator v0.1.0 (/home/eliza/Code/oxide/hubris/task/ereportulator)
error[E0080]: evaluation panicked: ringbufs may not be zero-length
    --> /rustlib/panic.rs:62:9
     |
  51 | pub macro panic_2021 {
     | -------------------- in this expansion of `$crate::panic::panic_2021!` (#3)
...
  62 |         $crate::panicking::panic_fmt($crate::const_format_args!($($t)+));
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `_` failed here
     |
    ::: lib/ringbuf/src/lib.rs:282:1
     |
 282 | macro_rules! ringbuf {
     | -------------------- in this expansion of `ringbuf::ringbuf!` (#1)
...
 293 |             assert!($n > 0, "ringbufs may not be zero-length");
     |             --------------------------------------------------
     |             |
     |             in this macro invocation (#2)
     |             in this macro invocation (#3)
     |
    ::: task/ereportulator/src/main.rs:72:1
     |
  72 | ringbuf::ringbuf!(__LOL, Trace, 0, Trace::None);
     | ----------------------------------------------- in this macro invocation (#1)
     |
    ::: /rustlib/macros/mod.rs:1691:5
     |
1691 |     macro_rules! assert {
     |     ------------------- in this expansion of `assert!` (#2)

For more information about this error, try `rustc --explain E0080`.
error: could not compile `task-ereportulator` (bin "task-ereportulator") due to 1 previous error
```