Use -Zallow-features to ensure we don't add more
This flag creates an allowlist of nightly features. By adding this to
the build, we'll get a failure if someone adds a new one, which gives us
the opportunity to really consider if we should be doing that.

Example output:

```
Caused by:
  the feature `foo_bar` is not in the list of allowed features:
  ["not_a_real_feature", "baz"]
  Error: failed to build jefe
```

Fixes #311